name: Lint

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          cache-dependency-path: week-4/dapp-voting/yarn.lock

      - name: Install dependencies
        run: yarn install --immutable
        working-directory: week-4/dapp-voting/

      # - name: Run hardhat node, deploy contracts (& generate contracts typescript output)
      #   run: yarn chain & yarn deploy
      #   working-directory: week-4/dapp-voting/

      - name: Run hardhat lint
        run: yarn hardhat:lint --max-warnings=0
        working-directory: week-4/dapp-voting/

      - name: Run nextjs lint
        run: yarn next:lint --max-warnings=0
        working-directory: week-4/dapp-voting/

      - name: Check typings on nextjs
        run: yarn next:check-types
        working-directory: week-4/dapp-voting/
