name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      project: ${{ steps.filter.outputs.project }}
      changes: ${{ steps.filter.outputs.changes }}
    strategy:
      matrix:
        path: ["week-4/dapp-voting", "week-5/dapp-lottery"]
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            project:
              - '${{ matrix.path }}/**'

  ci:
    needs: filter
    if: ${{ needs.filter.outputs.project == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ["week-4/dapp-voting", "week-5/dapp-lottery"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: ${{ matrix.path }}/yarn.lock

      - name: Install dependencies
        run: yarn install --immutable
        working-directory: ${{ matrix.path }}

      - name: Run hardhat node, deploy contracts (& generate contracts typescript output)
        run: yarn chain & yarn deploy
        working-directory: ${{ matrix.path }}

      - name: Run hardhat lint
        run: yarn hardhat:lint --max-warnings=0
        working-directory: ${{ matrix.path }}

      - name: Run nextjs lint
        run: yarn next:lint --max-warnings=0
        working-directory: ${{ matrix.path }}

      - name: Check typings on nextjs
        run: yarn next:check-types
        working-directory: ${{ matrix.path }}
